#!/usr/bin/env python3
"""gen_fleet_configs.py — deterministic fleet shard + config generator (run 2).

Fleet directive 2026-09-04 (orchestrator, RUN2-EXEC): full protocol
276 roles x 5 prompts x 240 questions, sharded across 8 worker boxes,
labels axis-run-14b-w1..w8. Shards are CONTIGUOUS chunks of the sorted
non-default role list, WEIGHTED by card class (relative S1 output tok/s,
temp/46 §3: A100_SXM4=3.0/GPU, RTX_6000Ada=1.15/GPU, L40S=1.0/GPU), so
all boxes finish S1 together. 'default' is appended to w1 (S5 needs it;
S5 itself runs centrally after coverage). Judge RPS per box is the shard-
proportional integer share of aggregate 48 (<=50 measured-safe ceiling).

Deterministic: same roles dir + same WORKERS table => same shards.
Extension recipe: adding roles later = new shard files over the SAME
bucket prefix (stages skip existing per-role outputs).
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
ROLES_DIR = HERE / "../../../submodules/assistant-axis/data/roles/instructions"

# worker -> (gpu_tier_string, num_gpus, weight_units, disk_gb, min_rel,
#            min_inet_down, s2_batch, max_dollars)
# Mix v2 (13:10 sweep, temp/45): the in-band single A100s vanished/failed
# the inet-cost cap; the live supply is a 4xA100_SXM4 slice at $1.67/GPU
# (coordinator's "A100 <=$2.00"), Ada singles/dual, L40S single/dual.
# Weight units per GPU: A100=3.0, Ada=1.15, L40S=1.0 (temp/46 §3).
WORKERS = {
    "w1": ("A100_SXM4:79:5.00:7.50", 4, 12.0, 300, 0.99, 1000, 4, 31),
    "w2": ("RTX_6000Ada:44:0.80:1.60", 2, 2.30, 150, 0.995, 1000, 2, 6),
    "w3": ("RTX_6000Ada:44:0.40:0.80", 1, 1.15, 100, 0.995, 1000, 2, 3),
    "w4": ("RTX_6000Ada:44:0.40:0.80", 1, 1.15, 100, 0.995, 1000, 2, 3),
    "w5": ("RTX_6000Ada:44:0.40:0.80", 1, 1.15, 100, 0.995, 1000, 2, 3),
    "w6": ("RTX_6000Ada:44:0.40:0.80", 1, 1.15, 100, 0.995, 1000, 2, 3),
    "w7": ("L40S:44:0.40:0.70", 1, 1.0, 100, 0.995, 500, 2, 3),
    "w8": ("L40S:44:0.80:1.70", 2, 2.0, 150, 0.995, 500, 2, 8),
}
AGG_JUDGE_RPS = 48

TEMPLATE = """# config.r1d-qwen-14b-{w}.env — run-2 FLEET worker {w} (GENERATED by
# tools/gen_fleet_configs.py — edit the generator, not this file).
# Full protocol 276x5x240 sharded; see temp/45-run2-exec.md.
MODEL_ID="deepseek-ai/DeepSeek-R1-Distill-Qwen-14B"
MODEL_TAG="r1d-qwen-14b-{w}"

GPU_TIERS="${{GPU_TIERS:-{tier}}}"
NUM_GPUS={num_gpus}
DISK_GB="${{DISK_GB:-{disk}}}"
MIN_RELIABILITY="${{MIN_RELIABILITY:-{rel}}}"
MIN_INET_DOWN="${{MIN_INET_DOWN:-{inet}}}"
MIN_INET_UP="${{MIN_INET_UP:-500}}"
MAX_INET_COST="${{MAX_INET_COST:-0.02}}"
MIN_CPU_RAM_GB="${{MIN_CPU_RAM_GB:-32}}"
GEO_FILTER="${{GEO_FILTER:-}}"

IMAGE="${{IMAGE:-vllm/vllm-openai:v0.13.0}}"
IMAGE_CUDA_MIN="${{IMAGE_CUDA_MIN:-12.8}}"
VLLM_PIN="0.13.0"
TORCH_PIN="2.9.0"
EXTRA_PIP_PINS="transformers==4.57.5 openai==2.15.0 safetensors==0.7.0 jsonlines==4.0.0 python-dotenv==1.2.1 tqdm==4.67.1 scikit-learn==1.7.2 scipy==1.15.3 joblib==1.5.3 threadpoolctl==3.6.0 plotly==6.5.1 narwhals==2.15.0 attrs==25.4.0"
INSTANCE_LABEL="axis-run-14b-{w}"

S2_BATCH="${{S2_BATCH:-{s2_batch}}}"
JUDGE_RPS="${{JUDGE_RPS:-{judge_rps}}}"
JUDGE_BATCH="${{JUDGE_BATCH:-20}}"
JUDGE_MODEL="gemini-flash-lite-latest"
SKIP_S5=1
STAGE1_EXTRA="${{STAGE1_EXTRA:---roles {roles}}}"
SLICE_ARGS="--roles accountant default --question_count 2"

MAX_HOURS="${{MAX_HOURS:-4.5}}"
WATCHDOG_GRACE_MIN="${{WATCHDOG_GRACE_MIN:-45}}"
HEARTBEAT_FRESH_MIN="${{HEARTBEAT_FRESH_MIN:-20}}"
MAX_DOLLARS="${{MAX_DOLLARS:-{max_dollars}}}"

BUCKET="hf://buckets/unrulyabstractions/persona-redteaming"
BUCKET_PREFIX="axis/r1d-qwen-14b"
PUSH_INTERVAL_SEC=300

REMOTE_ROOT=/workspace/axisrun
REMOTE_AA=/workspace/assistant-axis
OUT_DIR=/workspace/out
UPLOAD_DIR=/workspace/upload_stage
REMOTE_HF_HOME=/workspace/hf_cache

LOCAL_AA="$AXIS_LIB_HERE/../../../../submodules/assistant-axis"
AA_REQUIRED_COMMIT="3bb4ef1"
"""


def main():
    roles = sorted(p.stem for p in ROLES_DIR.glob("*.json"))
    assert "default" in roles, "default role missing"
    roles.remove("default")
    n = len(roles)
    total_w = sum(v[2] for v in WORKERS.values())
    # largest-remainder apportionment
    quotas = {w: n * v[2] / total_w for w, v in WORKERS.items()}
    counts = {w: int(q) for w, q in quotas.items()}
    for w, _ in sorted(quotas.items(), key=lambda kv: -(kv[1] - int(kv[1])))[
        : n - sum(counts.values())
    ]:
        counts[w] += 1
    assert sum(counts.values()) == n, (counts, n)

    shards, i = {}, 0
    for w in WORKERS:  # insertion order w1..w8
        shards[w] = roles[i : i + counts[w]]
        i += counts[w]
    shards["w1"] = shards["w1"] + ["default"]

    rps = {
        w: max(2, round(AGG_JUDGE_RPS * counts[w] / n)) for w in WORKERS
    }
    # keep the aggregate at AGG (the ceiling matters, not the split): the
    # largest worker absorbs the residual.
    big = max(counts, key=lambda w: counts[w])
    rps[big] += AGG_JUDGE_RPS - sum(rps.values())
    assert rps[big] >= 2
    print("aggregate judge rps:", sum(rps.values()))

    manifest = {"protocol": "276 roles x 5 prompts x 240 questions",
                "sharding": "sorted non-default roles, contiguous, weighted",
                "weights_units_per_gpu": {"A100_SXM4": 3.0, "RTX_6000Ada": 1.15,
                                          "L40S": 1.0},
                "workers": {}}
    for w, (tier, ng, wt, disk, rel, inet, s2b, maxd) in WORKERS.items():
        cfg = TEMPLATE.format(w=w, tier=tier, num_gpus=ng, disk=disk, rel=rel,
                              inet=inet, s2_batch=s2b, judge_rps=rps[w],
                              roles=" ".join(shards[w]), max_dollars=maxd)
        (HERE / f"config.r1d-qwen-14b-{w}.env").write_text(cfg)
        manifest["workers"][w] = {
            "tier": tier, "num_gpus": ng, "weight": wt, "n_roles": len(shards[w]),
            "judge_rps": rps[w], "s2_batch": s2b, "max_dollars": maxd,
            "roles_first": shards[w][0], "roles_last": shards[w][-1],
            "roles": shards[w],
        }
        print(f"{w}: {len(shards[w])} roles [{shards[w][0]}..{shards[w][-1]}] "
              f"rps={rps[w]} tier={tier} x{ng}")
    (HERE / "fleet_shards.json").write_text(json.dumps(manifest, indent=1))
    print("wrote fleet_shards.json + 8 config files")


if __name__ == "__main__":
    sys.exit(main())
